### ISSUE TITLE
add search

### ISSUE THREAD

**Issue by rootsmusic** [MikeCarlo/BusinessOps#11]
Please add a search for tool descriptions.  Thanks.

**Comment by JamesDBartlett3** [comment]
Hi @rootsmusic,

This is an interesting idea, and we'll certainly add this to our list of potential new features for a future release.

However, I should point out that it's already possible to search for text anywhere in the Business Ops app by opening the Dev Tools panel (Ctrl+Shift+I), and then using the Find function (Ctrl+F) just like you would on any webpage.

![image](https://user-images.githubusercontent.com/37491308/160707908-1e9d28d0-aac7-45ca-a81e-d740e883158a.png)

The reason this is possible is because Business Ops is built on the React and Electron frameworks, so it's really just a stripped-down Chromium browser window running a PWA with some extra OS integration stuff.

I hope this helps tide you over for now, until we can find time to develop and release an official search function in the app.

Cheers!
James

**Comment by JamesDBartlett3** [comment]
@rootsmusic, [the latest version of BusinessOps](https://github.com/MikeCarlo/BusinessOps/releases/latest) has a native search feature which does search the full description text of External Tools, like you requested. 
![image](https://github.com/user-attachments/assets/a95c25df-3db1-4127-ae42-5215dafce151)
